on:
  workflow_call:
    inputs:
      target:
        description: 'The rust target, i.e x86_64-unknown-linux-gnu'
        required: true
        type: string
      num_chunks:
        description: "The number of chunks to run for test-all-features"
        default: 1
        required: false
        type: number
      chunk:
        description: "The chunk number to run for test-all-features"
        default: 1
        required: false
        type: number

name: 🦀 Rust (Tier 2) 🦀

jobs:
  build-tier-2:
    name: 🧱 Build 🧱
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Checkout ✅
        uses: actions/checkout@v4
      - name: 🧰 Toolchain 🧰
        run: |
          rm -rf /home/runner/.cargo/bin/rustfmt
          rm -rf /home/runner/.cargo/bin/cargo-fmt
          rm -rf /home/runner/.cargo/bin/rust-analyzer
          rustup toolchain remove nightly-x86_64-unknown-linux-gnu
          rustup toolchain add nightly-x86_64-unknown-linux-gnu --profile minimal
          rustup target add ${{ inputs.target }}
          rustup default nightly
      - name: 💵 Rust Cache 💵
        uses: Swatinem/rust-cache@v2
        if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
        with:
          key: x86_64-unknown-linux-gnu
          cache-all-crates: true
      - name: 💾 Install (cargo-binstall) 💾
        uses: cargo-bins/cargo-binstall@main
      - name: 💾 Install (cargo-matrix) 💾
        run: cargo binstall --no-confirm --no-symlinks --no-discover-github-token cargo-matrix --force
      - name: 💾 Install (cross) 💾
        run: cargo binstall --no-confirm --no-symlinks cross --force
      - name: 🧱 Build 🧱
        run: cross matrix build --target=${{ inputs.target }}
