on:
  workflow_call:
    inputs:
      target:
        description: 'The rust target, i.e x86_64-unknown-linux-gnu'
        required: true
        type: string
      num_chunks:
        description: "The number of chunks to run for cargo-matrix"
        default: 1
        required: false
        type: number
      chunk:
        description: "The chunk number to run for cargo-matrix"
        default: 1
        required: false
        type: number
      project:
        description: 'The project to run cargo-matrix against (useful in workspaces)'
        default: ''
        required: false
        type: string

name: 🦀 Rust (Tier 2) 🦀

jobs:
  build-tier-2:
    name: 🧱 Build 🧱
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Checkout ✅
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: 🧰 Toolchain 🧰
        run: |
          rm -rf /home/runner/.cargo/bin/rustfmt
          rm -rf /home/runner/.cargo/bin/cargo-fmt
          rm -rf /home/runner/.cargo/bin/rust-analyzer
          rustup toolchain remove nightly-x86_64-unknown-linux-gnu
          rustup toolchain install nightly-x86_64-unknown-linux-gnu --profile minimal --no-self-update
          rustup target add ${{ inputs.target }}
          rustup default nightly
      - name: 💵 Rust Cache 💵
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
        with:
          key: x86_64-unknown-linux-gnu
          cache-all-crates: true
      - name: 💾 Install (cargo-binstall) 💾
        uses: cargo-bins/cargo-binstall@30b5ca8b54e1dcffd9548bc87ede1531310fdc67 # v1.20.0
      - name: 💾 Install (cargo-matrix) 💾
        env:
          GITHUB_TOKEN: ${{ github.token }}
          BINSTALL_MAXIMUM_RESOLUTION_TIMEOUT: "20"
        run: cargo binstall --no-confirm --no-symlinks cargo-matrix --force
      - name: 💾 Install (cross) 💾
        env:
          GITHUB_TOKEN: ${{ github.token }}
          BINSTALL_MAXIMUM_RESOLUTION_TIMEOUT: "20"
        run: cargo binstall --no-confirm --no-symlinks cross --force
      - name: 🧱 Build 🧱
        if: ${{ inputs.project == '' }}
        run: cross matrix --num-chunks ${{ inputs.num_chunks }} --chunk ${{ inputs.chunk }} build --target=${{ inputs.target }}
      - name: 🧱 Build P 🧱
        if: ${{ inputs.project != '' }}
        run: cross matrix --num-chunks ${{ inputs.num_chunks }} --chunk ${{ inputs.chunk }} -p ${{ inputs.project }} build --target=${{ inputs.target }}
